#! /bin/bash

notify() {
  notify-send -h string:x-canonical-private-synchronous:shot-notify -u low "Screenshot: Copied to clipboard"
}

screenshot() {
  grim -g "$(slurp)" -t png - | wl-copy
  notify
}

if [[ "$1" == "--area" ]]; then
  screenshot
fi


